# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0.xci
# IP: The module: 'uart_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0.xci
# IP: The module: 'uart_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SourceTree/AXI-Interface/ip_verify/uart_verify/uart_verify/uart_verify.srcs/sources_1/bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
