# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_axi_traffic_gen_0_0/uart_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_axi_traffic_gen_0_0 || ORIG_REF_NAME==uart_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_MASTER_0_0/uart_MASTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_MASTER_0_0 || ORIG_REF_NAME==uart_MASTER_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_SLAVE_0_0/uart_SLAVE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_SLAVE_0_0 || ORIG_REF_NAME==uart_SLAVE_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_DATA_uart_0_0/uart_DATA_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_DATA_uart_0_0 || ORIG_REF_NAME==uart_DATA_uart_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_clk_wiz_0_0/uart_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_clk_wiz_0_0 || ORIG_REF_NAME==uart_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_axi_uartlite_0_0/uart_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_axi_uartlite_0_0 || ORIG_REF_NAME==uart_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/uart/uart_ooc.xdc
